"""
Tests for openbrep.static_checker.

Each of the 4 checks has a positive (error caught) and negative (clean code passes) case.
Uses a lightweight FakeProject instead of a real HSFProject to avoid file I/O.
"""

import unittest
from openbrep.static_checker import StaticChecker, StaticCheckResult


class FakeParam:
    def __init__(self, name: str):
        self.name = name


class FakeProject:
    """Minimal stand-in for HSFProject used in tests."""

    def __init__(self, scripts: dict[str, str], param_names: list[str]):
        self._scripts = scripts  # {"3d.gdl": "...", "1d.gdl": "..."}
        self.parameters = [FakeParam(n) for n in param_names]

    def get_script(self, script_type) -> str:
        return self._scripts.get(script_type.value, "")


class TestUndefinedVar(unittest.TestCase):

    def test_undefined_var_detected(self):
        """Variable used in 3d.gdl that is not in paramlist.xml → error."""
        proj = FakeProject(
            scripts={"3d.gdl": "BLOCK width, depth, height\nEND\n"},
            param_names=["width", "depth"],  # height missing
        )
        result = StaticChecker().check(proj)
        self.assertFalse(result.passed)
        types = [e.check_type for e in result.errors]
        self.assertIn("undefined_var", types)
        details = " ".join(e.detail for e in result.errors)
        self.assertIn("height", details)

    def test_undefined_var_clean(self):
        """All variables declared → no undefined_var error."""
        proj = FakeProject(
            scripts={"3d.gdl": "BLOCK width, depth, height\nEND\n"},
            param_names=["width", "depth", "height"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [])

    def test_builtin_not_flagged(self):
        """GDL built-ins (SIN, MAX, etc.) must not be flagged as undefined."""
        proj = FakeProject(
            scripts={"3d.gdl": "x = SIN(MAX(A, B))\nBLOCK A, B, ZZYZX\nEND\n"},
            param_names=[],  # no user params — A/B/ZZYZX are reserved
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_file_metadata_not_flagged(self):
        """[FILE: ...] metadata lines must not produce undefined_var noise."""
        proj = FakeProject(
            scripts={"3d.gdl": "[FILE: scripts/3d.gdl]\nBLOCK width, depth, height\nEND\n"},
            param_names=["width", "depth", "height"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_comments_blank_and_metadata_ignored(self):
        """Blank lines, ! comments, and [FILE: ...] lines must be skipped together."""
        proj = FakeProject(
            scripts={
                "3d.gdl": "\n! generated by llm\n[FILE: scripts/3d.gdl]\n\nBLOCK width, depth, height ! inline note\nEND\n"
            },
            param_names=["width", "depth", "height"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_cross_script_assignment_with_metadata_not_flagged(self):
        """Cross-script assigned vars remain valid even when scripts start with [FILE: ...]."""
        proj = FakeProject(
            scripts={
                "1d.gdl": "[FILE: scripts/1d.gdl]\nheight = 10\n",
                "3d.gdl": "[FILE: scripts/3d.gdl]\nBLOCK width, depth, height\nEND\n",
            },
            param_names=["width", "depth"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_group_commands_and_names_not_flagged(self):
        """GROUP family commands and quoted group names must not be flagged as undefined."""
        proj = FakeProject(
            scripts={
                "3d.gdl": (
                    'GROUP "outerPot"\n'
                    'BLOCK A, B, ZZYZX\n'
                    'ENDGROUP\n'
                    'PLACEGROUP "outerPot"\n'
                    'SUBGROUP "outerPot"\n'
                    'END\n'
                )
            },
            param_names=[],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_values_and_lock_string_param_names_not_flagged(self):
        """Quoted parameter names in VALUES/LOCK should not be parsed as variables."""
        proj = FakeProject(
            scripts={
                "vl.gdl": 'VALUES "wall_thk" RANGE [0.01, 0.05]\nLOCK "wall_thk"\n'
            },
            param_names=["wall_thk"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_project2_not_flagged(self):
        """PROJECT2 in 2d.gdl is a built-in command and must not trigger undefined_var."""
        proj = FakeProject(
            scripts={"2d.gdl": "PROJECT2 3, 270, 2\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_textblock_and_paragraph_commands_not_flagged(self):
        """2D text commands generated by LLMs must not be treated as variables."""
        proj = FakeProject(
            scripts={
                "2d.gdl": (
                    'DEFINE STYLE "labelStyle" "Arial", 2, 5, 0\n'
                    'TEXTBLOCK labelTB, 10, 7, 0, 1, 1, "Label"\n'
                    'PARAGRAPH labelPara 2, 0, 0, 0, 1\n'
                    '  "Window label"\n'
                    'ENDPARAGRAPH\n'
                    'RICHTEXT2 0, 0, labelTB\n'
                )
            },
            param_names=["labelTB", "labelPara"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")

    def test_parameter_and_group_operation_commands_not_flagged(self):
        """Parameter and group operation keywords should be shared built-ins."""
        proj = FakeProject(
            scripts={
                "1d.gdl": (
                    'VALUES "open_mode" 1, 2, 3\n'
                    'VALUES "frame_depth" RANGE [0.02, 0.30]\n'
                    'LOCK "frame_depth"\n'
                    'PARAMETERS frame_depth = MAX(frame_depth, 0.02)\n'
                    'GROUP_OPERATION 3\n'
                )
            },
            param_names=["open_mode", "frame_depth"],
        )
        result = StaticChecker().check(proj)
        undef = [e for e in result.errors if e.check_type == "undefined_var"]
        self.assertEqual(undef, [], msg=f"Unexpected: {undef}")


class TestForwardDecl(unittest.TestCase):

    def test_forward_decl_detected(self):
        """_prefixed var used in 3d.gdl but not assigned in 1d.gdl → error."""
        proj = FakeProject(
            scripts={
                "3d.gdl": "BLOCK _thk, _dep, height\nEND\n",
                "1d.gdl": "_thk = thk\n",   # _dep missing
            },
            param_names=["thk", "dep", "height"],
        )
        result = StaticChecker().check(proj)
        types = [e.check_type for e in result.errors]
        self.assertIn("forward_decl", types)
        details = " ".join(e.detail for e in result.errors if e.check_type == "forward_decl")
        self.assertIn("_dep", details)

    def test_forward_decl_clean(self):
        """All _vars assigned in 1d.gdl → no forward_decl error."""
        proj = FakeProject(
            scripts={
                "3d.gdl": "BLOCK _thk, _dep, height\nEND\n",
                "1d.gdl": "_thk = thk\n_dep = dep\n",
            },
            param_names=["thk", "dep", "height"],
        )
        result = StaticChecker().check(proj)
        fwd = [e for e in result.errors if e.check_type == "forward_decl"]
        self.assertEqual(fwd, [])

    def test_forward_decl_metadata_not_flagged(self):
        """[FILE: ...] metadata lines must not create forward_decl noise."""
        proj = FakeProject(
            scripts={
                "3d.gdl": "[FILE: scripts/3d.gdl]\nBLOCK _thk, height\nEND\n",
                "1d.gdl": "[FILE: scripts/1d.gdl]\n_thk = thk\n",
            },
            param_names=["thk", "height"],
        )
        result = StaticChecker().check(proj)
        fwd = [e for e in result.errors if e.check_type == "forward_decl"]
        self.assertEqual(fwd, [], msg=f"Unexpected: {fwd}")


class TestStackImbalance(unittest.TestCase):

    def test_stack_imbalance_detected(self):
        """ADD without matching DEL → stack_imbalance error."""
        proj = FakeProject(
            scripts={"3d.gdl": "ADD 1, 0, 0\nBLOCK 1,1,1\n! no DEL\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        types = [e.check_type for e in result.errors]
        self.assertIn("stack_imbalance", types)
        detail = next(e.detail for e in result.errors if e.check_type == "stack_imbalance")
        self.assertIn("push(1)", detail)
        self.assertIn("pop(0)", detail)

    def test_stack_balanced(self):
        """Balanced ADD/DEL → no stack_imbalance error."""
        proj = FakeProject(
            scripts={"3d.gdl": "ADD 1,0,0\nBLOCK 1,1,1\nDEL 1\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        si = [e for e in result.errors if e.check_type == "stack_imbalance"]
        self.assertEqual(si, [])

    def test_stack_multiple_pushes(self):
        """ADDX + ADDY + 2×DEL → balanced."""
        proj = FakeProject(
            scripts={"3d.gdl": "ADDX 1\nADDY 2\nBLOCK 1,1,1\nDEL 2\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        si = [e for e in result.errors if e.check_type == "stack_imbalance"]
        self.assertEqual(si, [])

    def test_plain_add_counts_as_push(self):
        """Three-argument ADD must count as one push."""
        proj = FakeProject(
            scripts={"3d.gdl": "ADD 1, 2, 3\nBLOCK 1,1,1\nDEL 1\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        si = [e for e in result.errors if e.check_type == "stack_imbalance"]
        self.assertEqual(si, [])

    def test_plain_add_and_addz_balance_two_dels(self):
        """ADD + ADDZ + DEL 1 + DEL 1 should be treated as balanced."""
        proj = FakeProject(
            scripts={"3d.gdl": "ADD 1, 2, 0\nADDZ 3\nBLOCK 1,1,1\nDEL 1\nDEL 1\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        si = [e for e in result.errors if e.check_type == "stack_imbalance"]
        self.assertEqual(si, [])


class TestBlockMismatch(unittest.TestCase):

    def test_if_endif_mismatch_detected(self):
        """Unclosed IF block → block_mismatch error."""
        proj = FakeProject(
            scripts={"3d.gdl": "IF A > 1 THEN\n  BLOCK 1,1,1\n! missing ENDIF\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        types = [e.check_type for e in result.errors]
        self.assertIn("block_mismatch", types)
        detail = next(e.detail for e in result.errors if e.check_type == "block_mismatch")
        self.assertIn("ENDIF", detail)

    def test_for_next_mismatch_detected(self):
        """FOR without NEXT → block_mismatch error."""
        proj = FakeProject(
            scripts={"3d.gdl": "FOR i = 1 TO 3\n  BLOCK 1,1,1\n! missing NEXT\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        types = [e.check_type for e in result.errors]
        self.assertIn("block_mismatch", types)
        detail = next(e.detail for e in result.errors if e.check_type == "block_mismatch")
        self.assertIn("NEXT", detail)

    def test_single_line_if_not_counted(self):
        """Single-line IF THEN does not require ENDIF."""
        proj = FakeProject(
            scripts={"3d.gdl": "IF A > 0 THEN BLOCK 1,1,1\nEND\n"},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        bm = [e for e in result.errors if e.check_type == "block_mismatch"]
        self.assertEqual(bm, [], msg=f"Unexpected: {bm}")

    def test_block_clean(self):
        """Properly matched IF/ENDIF and FOR/NEXT → no block_mismatch."""
        proj = FakeProject(
            scripts={"3d.gdl": (
                "IF A > 1 THEN\n"
                "  FOR i = 1 TO 3\n"
                "    BLOCK 1,1,1\n"
                "  NEXT i\n"
                "ENDIF\n"
                "END\n"
            )},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        bm = [e for e in result.errors if e.check_type == "block_mismatch"]
        self.assertEqual(bm, [])

    def test_block_count_ignores_metadata_lines(self):
        """[FILE: ...], blank lines, and comments must not affect block counts."""
        proj = FakeProject(
            scripts={"3d.gdl": (
                "[FILE: scripts/3d.gdl]\n"
                "\n"
                "! metadata above should be ignored\n"
                "IF A > 1 THEN\n"
                "  FOR i = 1 TO 3\n"
                "    BLOCK 1,1,1\n"
                "  NEXT i\n"
                "ENDIF\n"
                "END\n"
            )},
            param_names=[],
        )
        result = StaticChecker().check(proj)
        bm = [e for e in result.errors if e.check_type == "block_mismatch"]
        self.assertEqual(bm, [], msg=f"Unexpected: {bm}")


class TestEdgeCases(unittest.TestCase):

    def test_none_project_passes(self):
        """None project must return passed=True without raising."""
        result = StaticChecker().check(None)
        self.assertTrue(result.passed)
        self.assertEqual(result.errors, [])

    def test_empty_scripts_pass(self):
        """Project with no script content should pass all checks."""
        proj = FakeProject(scripts={}, param_names=["width"])
        result = StaticChecker().check(proj)
        self.assertTrue(result.passed)


class TestStackImbalanceBranchAware(unittest.TestCase):
    """Branch-aware stack check: IF branch delta asymmetry."""

    def _branch_errors(self, code_3d: str):
        proj = FakeProject(scripts={"3d.gdl": code_3d}, param_names=[])
        return [e for e in StaticChecker().check(proj).errors if e.check_type == "stack_imbalance"]

    def test_symmetric_if_else_passes(self):
        """Both branches push and pop equally → no error."""
        code = (
            "IF a > 0 THEN\n"
            "  ADD 0, 0, 1\n"
            "  BLOCK 1, 1, 1\n"
            "  DEL\n"
            "ELSE\n"
            "  ADD 0, 0, 1\n"
            "  SPHERE 0.5\n"
            "  DEL\n"
            "ENDIF\n"
            "END\n"
        )
        self.assertEqual(self._branch_errors(code), [])

    def test_then_push_else_pop_global_balanced_detected(self):
        """
        True false negative for global check:
          THEN: ADD (push+1, no DEL)
          ELSE: DEL (no ADD, pop-1)
          Global count: push=1, pop=1 → globally balanced, but both paths are broken.
        Branch-aware check must catch the asymmetry (THEN delta=+1, ELSE delta=-1).
        """
        code = (
            "IF a > 0 THEN\n"
            "  ADD 0, 0, 1\n"    # push in THEN only, delta THEN = +1
            "  BLOCK 1, 1, 1\n"
            "ELSE\n"
            "  BLOCK 1, 1, 1\n"
            "  DEL\n"            # pop in ELSE only, delta ELSE = -1
            "ENDIF\n"
            "END\n"
        )
        errs = self._branch_errors(code)
        branch_errs = [e for e in errs if "IF 分支" in e.detail]
        self.assertTrue(len(branch_errs) >= 1, f"Expected branch error; got: {errs}")

    def test_else_branch_missing_del_detected(self):
        """
        True false negative for global check:
          THEN: ADD + DEL (balanced, delta=0)
          ELSE: ADD only (no DEL, delta=+1) but a DEL sits outside ENDIF.
          Global: push=2 (THEN+ELSE), pop=2 (THEN's DEL + outside DEL) → balanced.
          Branch check: THEN delta=0, ELSE delta=+1 → asymmetric → error.
        """
        code = (
            "IF a > 0 THEN\n"
            "  ADD 0, 0, 1\n"
            "  BLOCK 1, 1, 1\n"
            "  DEL\n"            # delta THEN = 0
            "ELSE\n"
            "  ADD 0, 0, 1\n"   # push in ELSE, no DEL inside branch
            "  BLOCK 1, 1, 1\n" # delta ELSE = +1
            "ENDIF\n"
            "DEL\n"             # global pop compensates → global push=2, pop=2
            "END\n"
        )
        errs = self._branch_errors(code)
        branch_errs = [e for e in errs if "IF 分支" in e.detail]
        self.assertTrue(len(branch_errs) >= 1, f"Expected branch error; got: {errs}")

    def test_if_without_else_balanced_passes(self):
        """IF without ELSE: THEN delta=0 matched against implicit ELSE delta=0 → passes."""
        code = (
            "IF a > 0 THEN\n"
            "  ADD 0, 0, 1\n"
            "  BLOCK 1, 1, 1\n"
            "  DEL\n"
            "ENDIF\n"
            "END\n"
        )
        errs = self._branch_errors(code)
        self.assertEqual(errs, [], "Balanced IF without ELSE should not trigger branch error")

    def test_single_line_if_not_tracked(self):
        """Single-line IF THEN <code> has no ENDIF → no branch frame opened."""
        code = (
            "IF a > 0 THEN ADD 0, 0, 1\n"
            "DEL\n"
            "END\n"
        )
        errs = self._branch_errors(code)
        self.assertEqual(errs, [])

    def test_delall_skips_branch_check(self):
        """DELALL present → entire branch check is skipped (no false positives)."""
        code = (
            "ADD 0, 0, 1\n"
            "IF a > 0 THEN\n"
            "  ADD 0, 0, 1\n"
            "ELSE\n"
            "  DELALL\n"
            "ENDIF\n"
            "END\n"
        )
        errs = self._branch_errors(code)
        self.assertEqual(errs, [])

    def test_nested_if_balanced_passes(self):
        """Nested IF that is balanced contributes zero net delta to parent → no error."""
        code = (
            "IF outer > 0 THEN\n"
            "  ADD 0, 0, 1\n"
            "  IF inner > 0 THEN\n"
            "    BLOCK 1, 1, 1\n"
            "  ELSE\n"
            "    SPHERE 0.5\n"
            "  ENDIF\n"
            "  DEL\n"
            "ELSE\n"
            "  CONE 1, 0.5, 1\n"
            "ENDIF\n"
            "END\n"
        )
        errs = self._branch_errors(code)
        self.assertEqual(errs, [], "Balanced nested IF should not trigger branch error")


if __name__ == "__main__":
    unittest.main()
