import unittest

from openbrep.cross_script_checker import CrossScriptChecker
from openbrep.hsf_project import HSFProject, GDLParameter, ScriptType


class TestCrossScriptChecker(unittest.TestCase):
    def _make_project(
        self,
        *,
        script_3d: str,
        script_1d: str = "",
        param_names: list[str] | None = None,
    ) -> HSFProject:
        project = HSFProject("test_object")
        project.parameters = [
            GDLParameter(name=name, type_tag="Length", value="1.0")
            for name in (param_names or [])
        ]
        if script_1d:
            project.set_script(ScriptType.MASTER, script_1d)
        project.set_script(ScriptType.SCRIPT_3D, script_3d)
        return project

    def test_file_metadata_not_reported_as_cross_script_warning(self):
        project = self._make_project(
            script_3d="[FILE: scripts/3d.gdl]\nBLOCK width, depth, height\nEND\n",
            param_names=["width", "depth", "height"],
        )

        issues = CrossScriptChecker().check(project)

        self.assertEqual(issues, [])

    def test_comments_not_reported_as_cross_script_warning(self):
        project = self._make_project(
            script_3d=(
                "! generated by llm\n"
                "BLOCK width, depth, height ! inline unknownName\n"
                "END\n"
            ),
            param_names=["width", "depth", "height"],
        )

        issues = CrossScriptChecker().check(project)

        self.assertEqual(issues, [])

    def test_master_assigned_name_not_reported_as_cross_script_warning(self):
        project = self._make_project(
            script_1d="derivedHeight = height\n",
            script_3d="BLOCK width, depth, derivedHeight\nEND\n",
            param_names=["width", "depth", "height"],
        )

        issues = CrossScriptChecker().check(project)

        self.assertEqual(issues, [])

    def test_unknown_name_still_reported_as_cross_script_warning(self):
        project = self._make_project(
            script_3d="BLOCK width, depth, missingHeight\nEND\n",
            param_names=["width", "depth"],
        )

        issues = CrossScriptChecker().check(project)

        self.assertEqual(len(issues), 1)
        issue = issues[0]
        self.assertEqual(issue.level, "warning")
        self.assertEqual(issue.category, "cross_script")
        self.assertEqual(issue.file, "3d.gdl")
        self.assertIn("MISSINGHEIGHT", issue.message)


if __name__ == "__main__":
    unittest.main()
