"""
BS2G Generator — IR → GDL scripts + paramlist.

Assembles mapper output into complete, stack-balanced GDL.
Strategy: every primitive gets its own ADD/DEL scope so the
transform stack is always balanced regardless of nesting depth.
"""

from __future__ import annotations

import re

from openbrep.hsf_project import GDLParameter
from openbrep.importers.blender_script.ir import (
    IRAssignment,
    IRCondition,
    IRLoop,
    IRNode,
    IRPrimitive,
    IRScript,
    IRTransform,
    IRUnsupported,
)
from openbrep.importers.blender_script.mapper import (
    map_primitive,
    map_transform,
    primitive_half_extents,
)


# ── 3D script generation ────────────────────────────────────


def generate_gdl_3d(ir: IRScript) -> str:
    """
    Generate a complete 3d.gdl script from an IRScript.

    Guarantees:
    - ADD/DEL stack is balanced (every push has a matching pop).
    - Each primitive is drawn in its own scoped block.
    - Unsupported operations become GDL comments.
    """
    lines = [
        f"! Generated by BS2G from Blender script: {ir.function_name}",
        f"! Parameters: {', '.join(p.name for p in ir.parameters)}",
        "",
    ]

    # Emit local variable assignments (derived values)
    emitted_vars: set[str] = set()
    for name, value in ir.local_vars.items():
        lines.append(f"{name} = {value}")
        emitted_vars.add(name)
    if ir.local_vars:
        lines.append("")

    # Group body nodes: associate transforms with their preceding primitive
    groups = _group_nodes(ir.body)
    for group in groups:
        lines.extend(_emit_group(group, indent=0, emitted_vars=emitted_vars))

    lines.append("")
    lines.append("END")
    return "\n".join(lines) + "\n"


# ── Node grouping ───────────────────────────────────────────
#
# Blender scripts follow a pattern:
#   primitive_add()
#   obj = bpy.context.object
#   obj.scale = (...)
#   obj.location = (...)
#
# We group a primitive with its following transforms so the
# generator can wrap them in a single scoped block.


class _PrimitiveGroup:
    """A primitive with its associated transforms."""

    def __init__(self, primitive: IRPrimitive):
        self.primitive = primitive
        self.transforms: list[IRTransform] = []


class _StandaloneNode:
    """A node that is not part of a primitive group."""

    def __init__(self, node: IRNode):
        self.node = node


_Group = _PrimitiveGroup | _StandaloneNode


def _group_nodes(nodes: list[IRNode]) -> list[_Group]:
    """Group primitives with their following transforms."""
    groups: list[_Group] = []
    current: _PrimitiveGroup | None = None

    for node in nodes:
        if isinstance(node, IRPrimitive):
            # Start a new primitive group
            current = _PrimitiveGroup(node)
            groups.append(current)

        elif isinstance(node, IRTransform) and current is not None:
            # Attach transform to the current primitive
            current.transforms.append(node)

        elif isinstance(node, IRAssignment) and current is not None:
            # Skip Blender bookkeeping like "obj = bpy.context.object"
            if "bpy.context" in node.value:
                continue
            # Other assignments break the group
            current = None
            groups.append(_StandaloneNode(node))

        else:
            # Non-transform node breaks the group
            current = None
            groups.append(_StandaloneNode(node))

    return groups


# ── Emission ────────────────────────────────────────────────


def _emit_group(group: _Group, indent: int, emitted_vars: set[str]) -> list[str]:
    """Emit a grouped or standalone node."""
    if isinstance(group, _PrimitiveGroup):
        return _emit_primitive_group(group, indent, emitted_vars)
    return _emit_node(group.node, indent, emitted_vars)


def _emit_primitive_group(group: _PrimitiveGroup, indent: int, emitted_vars: set[str]) -> list[str]:
    """
    Emit a primitive with its transforms as a scoped block.

    Structure:
        ADD location        (if translate transform exists)
        MUL scale           (if scale transform exists)
        ADD -half, -half, -half   (centering)
        BLOCK/CYLIND/...    (geometry)
        DEL 1               (undo centering)
        DEL 1               (undo scale)
        DEL 1               (undo location)
    """
    pad = "    " * indent
    lines: list[str] = []
    push_count = 0

    # Separate transforms by kind for correct ordering
    translate = None
    scale = None
    rotate = None
    for t in group.transforms:
        if t.kind == "translate":
            translate = t
        elif t.kind == "scale":
            scale = t
        elif t.kind == "rotate":
            rotate = t

    # Push order: translate → rotate → scale (outermost to innermost)
    if translate:
        push, _ = map_transform(translate)
        lines.append(f"{pad}{push}")
        push_count += 1

    if rotate:
        push, _ = map_transform(rotate)
        lines.append(f"{pad}{push}")
        push_count += 1

    if scale:
        push, _ = map_transform(scale)
        lines.append(f"{pad}{push}")
        push_count += 1

    # Centering offset (Blender primitives are centred, GDL grows from origin)
    hx, hy, hz = primitive_half_extents(group.primitive)
    lines.append(f"{pad}ADD -{hx}, -{hy}, -{hz}")
    push_count += 1

    # Geometry
    geom = map_primitive(group.primitive)
    lines.append(f"{pad}{geom}")

    # Pop everything
    if push_count > 0:
        lines.append(f"{pad}DEL {push_count}")

    return lines


def _emit_node(node: IRNode, indent: int, emitted_vars: set[str]) -> list[str]:
    """Emit a single IR node as GDL lines."""
    pad = "    " * indent

    if isinstance(node, IRPrimitive):
        # Standalone primitive (no transforms)
        hx, hy, hz = primitive_half_extents(node)
        geom = map_primitive(node)
        return [
            f"{pad}ADD -{hx}, -{hy}, -{hz}",
            f"{pad}{geom}",
            f"{pad}DEL 1",
        ]

    if isinstance(node, IRTransform):
        push, pop = map_transform(node)
        return [f"{pad}{push}", f"{pad}{pop}"]

    if isinstance(node, IRAssignment):
        # Skip bpy.context bookkeeping
        if "bpy.context" in node.value:
            return []
        # Skip already-emitted vars (dedup local_vars declarations)
        if node.name in emitted_vars:
            return []
        emitted_vars.add(node.name)
        return [f"{pad}{node.name} = {node.value}"]

    if isinstance(node, IRLoop):
        return _emit_loop(node, indent, emitted_vars)

    if isinstance(node, IRCondition):
        return _emit_condition(node, indent, emitted_vars)

    if isinstance(node, IRUnsupported):
        return [
            f"{pad}! [BS2G-UNSUPPORTED] {_sanitize_comment(node.operation)}",
            f"{pad}! Reason: {_sanitize_comment(node.reason)}",
            f"{pad}! Source line {node.line}: {_sanitize_comment(node.source_line)}",
            f"{pad}! This section requires manual implementation",
        ]

    return [f"{pad}! [BS2G] Unhandled node: {type(node).__name__}"]


# Dotted Python attribute paths (bpy.ops.x, math.log, …) must not appear
# anywhere in generated GDL — not even in comments: the purity gate scans
# the whole file for them.
_PY_PATH_RE = re.compile(r"\b[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+\b")


def _sanitize_comment(text: str) -> str:
    """Rewrite dotted Python paths in comment text as spaced words."""
    return _PY_PATH_RE.sub(lambda m: m.group(0).replace(".", " "), text)


def _emit_loop(node: IRLoop, indent: int, emitted_vars: set[str]) -> list[str]:
    """Emit a FOR/NEXT loop with balanced transforms inside."""
    pad = "    " * indent

    header = f"{pad}FOR {node.var_name} = {node.start} TO {node.end}"
    if node.step:
        header += f" STEP {node.step}"
    lines = [header]

    # Group and emit body
    groups = _group_nodes(node.body)
    for group in groups:
        lines.extend(_emit_group(group, indent + 1, emitted_vars))

    lines.append(f"{pad}NEXT {node.var_name}")
    return lines


def _emit_condition(node: IRCondition, indent: int, emitted_vars: set[str]) -> list[str]:
    """Emit an IF/THEN/ELSE/ENDIF block."""
    pad = "    " * indent
    inner = "    " * (indent + 1)

    lines = [f"{pad}IF {node.condition} THEN"]

    groups = _group_nodes(node.then_body)
    for group in groups:
        lines.extend(_emit_group(group, indent + 1, emitted_vars))

    if node.else_body:
        lines.append(f"{pad}ELSE")
        groups = _group_nodes(node.else_body)
        for group in groups:
            lines.extend(_emit_group(group, indent + 1, emitted_vars))

    lines.append(f"{pad}ENDIF")
    return lines


# ── Paramlist generation ────────────────────────────────────


def generate_paramlist(ir: IRScript) -> list[GDLParameter]:
    """
    Convert IR parameters to GDLParameter list for paramlist.xml.

    Prepends the standard ArchiCAD reserved parameters (A, B, ZZYZX)
    and maps each IR parameter to its GDL type.
    """
    params: list[GDLParameter] = [
        GDLParameter("A", "Length", "Width", "1.00", is_fixed=True),
        GDLParameter("B", "Length", "Depth", "1.00", is_fixed=True),
        GDLParameter("ZZYZX", "Length", "Height", "1.00", is_fixed=True),
    ]

    for p in ir.parameters:
        # Map GDL type to paramlist type tag
        type_tag = p.gdl_type
        value = p.default_value

        # Boolean: GDL uses 0/1
        if type_tag == "Boolean":
            value = "1" if value in ("True", "true", "1") else "0"

        params.append(GDLParameter(
            name=p.name,
            type_tag=type_tag,
            description=f"From Blender script parameter",
            value=value,
        ))

    return params


# ── 2D fallback ─────────────────────────────────────────────


def generate_fallback_2d() -> str:
    """
    Generate a minimal 2D script as a fallback.

    Used when LLM completion is unavailable or fails.
    Provides hotspots and a projected view.
    """
    return "\n".join([
        "! Fallback 2D script — replace with proper 2D symbol",
        "HOTSPOT2 0, 0",
        "HOTSPOT2 A, 0",
        "HOTSPOT2 0, B",
        "HOTSPOT2 A, B",
        "PROJECT2 3, 270, 2",
        "",
    ])
