"""
BS2G LLM Completion Layer.

Uses the LLM to generate parts that the rule engine cannot:
  - 2D script (Blender has no 2D concept)
  - Master script derived variables (optional)

The LLM never touches the 3D script — that is the rule engine's
deterministic output.
"""

from __future__ import annotations

import logging
from typing import Optional, TYPE_CHECKING

from openbrep.importers.blender_script.generator import generate_fallback_2d
from openbrep.importers.blender_script.ir import IRScript, IRUnsupported

if TYPE_CHECKING:
    from openbrep.llm import LLMAdapter

logger = logging.getLogger(__name__)


def complete_with_llm(
    ir: IRScript,
    generated_3d: str,
    paramlist_xml: str,
    llm: "LLMAdapter",
) -> dict[str, str]:
    """
    Use the LLM to generate 2D (and optionally master) scripts.

    Args:
        ir: Parsed intermediate representation.
        generated_3d: The rule-engine-generated 3d.gdl content.
        paramlist_xml: The generated paramlist.xml content.
        llm: An initialised LLMAdapter instance.

    Returns:
        Dict mapping script filenames to content, e.g.
        {"scripts/2d.gdl": "...", "scripts/1d.gdl": "..."}.
        Falls back to minimal 2D on LLM failure.
    """
    warnings_text = _format_warnings(ir.warnings)

    prompt = f"""\
You are completing a GDL library part converted from a Blender Python script.

The 3D script has been generated by a deterministic rule engine. DO NOT modify it:
```gdl
{generated_3d}
```

The parameter list (paramlist.xml) is:
```xml
{paramlist_xml}
```

Your tasks:
1. Generate a 2D script (scripts/2d.gdl) for the plan-view symbol.
   - MUST include PROJECT2 3, 270, 2 for projected view
   - MUST include HOTSPOT2 at corners (0,0), (A,0), (0,B), (A,B)
   - Use LINE2, RECT2, CIRCLE2 for additional 2D detail as appropriate
   - Reference parameters from the paramlist (A, B, ZZYZX, and user params)

2. If there are derived variables that need calculation, generate a
   Master script (scripts/1d.gdl) with those calculations.

{_format_warnings_section(ir.warnings)}

Respond with ONLY the script contents, clearly labelled:
--- 2d.gdl ---
<content>
--- 1d.gdl ---
<content>
"""

    try:
        from openbrep.llm import Message
        response = llm.generate([
            Message(role="system", content=(
                "You are a GDL (Geometric Description Language) expert for ArchiCAD "
                "library parts. Generate clean, correct GDL scripts. "
                "Use only standard GDL keywords. Ensure all variables are declared "
                "in the paramlist or computed in the master script."
            )),
            Message(role="user", content=prompt),
        ])

        if response and response.content:
            return _parse_llm_scripts(response.content)

    except Exception as exc:
        logger.warning("BS2G LLM completion failed: %s", exc)

    # Fallback
    return {"scripts/2d.gdl": generate_fallback_2d()}


def _format_warnings(warnings: list[IRUnsupported]) -> str:
    """Format warnings for inclusion in the LLM prompt."""
    if not warnings:
        return ""
    lines = ["The following operations could not be converted:"]
    for w in warnings:
        lines.append(f"  - Line {w.line}: {w.operation} — {w.reason}")
    return "\n".join(lines)


def _format_warnings_section(warnings: list[IRUnsupported]) -> str:
    """Format warnings as a prompt section."""
    if not warnings:
        return "No unsupported operations — the 3D conversion was complete."
    text = _format_warnings(warnings)
    return (
        "Note: the following operations were not converted and may affect "
        "the 2D representation:\n" + text
    )


def _parse_llm_scripts(content: str) -> dict[str, str]:
    """Parse LLM response into script files."""
    scripts: dict[str, str] = {}
    current_file: Optional[str] = None
    current_lines: list[str] = []

    for line in content.splitlines():
        stripped = line.strip()

        # Detect file markers
        if stripped.startswith("--- ") and stripped.endswith(" ---"):
            # Save previous
            if current_file and current_lines:
                scripts[current_file] = "\n".join(current_lines) + "\n"
            current_file = "scripts/" + stripped[4:-4].strip()
            current_lines = []
            continue

        if current_file is not None:
            current_lines.append(line)

    # Save last
    if current_file and current_lines:
        scripts[current_file] = "\n".join(current_lines) + "\n"

    # Ensure 2D exists
    if "scripts/2d.gdl" not in scripts:
        scripts["scripts/2d.gdl"] = generate_fallback_2d()

    return scripts
