"""
BS2G loft → GDL emitter — LoftModel → RULED{2} chain.

Each adjacent ring pair becomes one ``RULED{2}`` segment: the base
polyline is the lower ring in the local x-y plane (after ``ADDZ``),
the space curve is the upper ring.  Ring planes perpendicular to the
X or Y axis are rotated into Z-plane form by a proper (orientation
preserving) coordinate permutation, so no GDL rotation is needed.

Mask: 52 (j3 side + j5 + j6 edges visible, smooth surface); the first
segment adds j1 (base cap), the last adds j2 (top cap), which replaces
the source script's triangle-fan end caps.
"""

from __future__ import annotations

from openbrep.importers.blender_script.loft_detect import LoftModel

_BASE_MASK = 4 + 16 + 32  # j3 side surface + j5/j6 curve edges visible


def generate_loft_3d(
    model: LoftModel,
    *,
    scale: float = 1.0,
    source_name: str = "",
) -> str:
    """Emit a complete 3d.gdl script for *model* as a RULED{2} chain."""
    if len(model.rings) < 2:
        raise ValueError("放样至少需要 2 个截面环")

    rings = [
        [_permute(p, model.axis) for p in ring]
        for ring in model.rings
    ]
    ring_z = [_mean_axis(ring, 2) for ring in rings]
    n = len(rings[0])

    lines = [
        f"! Generated by BS2G mesh/loft mode: {source_name}",
        f"! Sections: {len(rings)} rings x {n} pts, scale={_fmt(scale)}",
    ]

    bbox = _bbox(rings, scale)
    if max(bbox) > 100 and scale == 1.0:
        lines.append(
            "! WARNING: 最大尺寸 "
            f"{_fmt(max(bbox))} m 超过 100 m，坐标疑似毫米，考虑 scale=0.001"
        )
    lines.append("")

    last = len(rings) - 2
    for k in range(len(rings) - 1):
        dz = (ring_z[k + 1] - ring_z[k]) * scale
        mask = _BASE_MASK + (1 if k == 0 else 0) + (2 if k == last else 0)
        lines.append(f"ADDZ {_fmt(ring_z[k] * scale)}")
        lines.append(f"RULED{{2}} {n}, {mask},")
        nums: list[str] = []
        for p in rings[k]:
            nums += [_fmt(p[0] * scale), _fmt(p[1] * scale), "0"]
        for p in rings[k + 1]:
            nums += [_fmt(p[0] * scale), _fmt(p[1] * scale), _fmt(dz)]
        lines.extend(_wrap_numbers(nums))
        lines.append("DEL 1")

    lines.append("")
    lines.append("END")
    return "\n".join(lines) + "\n"


def loft_bbox_params(
    model: LoftModel,
    scale: float = 1.0,
) -> tuple[str, str, str]:
    """Bounding-box dimensions (A, B, ZZYZX) for the paramlist."""
    rings = [
        [_permute(p, model.axis) for p in ring]
        for ring in model.rings
    ]
    bbox = _bbox(rings, scale)
    return _fmt(bbox[0]), _fmt(bbox[1]), _fmt(bbox[2])


# ── Internals ───────────────────────────────────────────────


def _permute(
    p: tuple[float, float, float], axis: int
) -> tuple[float, float, float]:
    """Rotate coordinates so the loft axis becomes +Z (proper rotation)."""
    if axis == 2:
        return p
    if axis == 1:
        x, y, z = p
        return (x, -z, y)
    # axis == 0
    x, y, z = p
    return (y, z, x)


def _mean_axis(ring: list[tuple[float, float, float]], axis: int) -> float:
    return sum(p[axis] for p in ring) / len(ring)


def _bbox(rings: list[list[tuple[float, float, float]]], scale: float) -> tuple[float, float, float]:
    pts = [p for ring in rings for p in ring]
    mins = [min(p[a] for p in pts) for a in range(3)]
    maxs = [max(p[a] for p in pts) for a in range(3)]
    return tuple((maxs[a] - mins[a]) * scale for a in range(3))


def _wrap_numbers(nums: list[str], per_line: int = 8) -> list[str]:
    """Chunk numbers into continuation lines (trailing commas)."""
    lines: list[str] = []
    for i in range(0, len(nums), per_line):
        chunk = ", ".join(nums[i:i + per_line])
        if i + per_line < len(nums):
            chunk += ","
        lines.append("    " + chunk)
    return lines


def _fmt(value: float) -> str:
    """Fixed-point formatting, no scientific notation, trimmed zeros."""
    v = float(value)
    if abs(v) < 5e-7:
        v = 0.0
    s = f"{v:.6f}".rstrip("0").rstrip(".")
    if s in ("", "-0"):
        return "0"
    return s
