"""
BS2G arbitrary-mesh → GDL emitter — CapturedMesh → low-level topology body.

Universal static fallback for bmesh scripts whose geometry is not a
recognisable loft: every vertex becomes a ``VERT``, every unique edge an
``EDGE``, every face a ``PGON``, closed by ``BODY -1``.  The simplified
form (vect=0 / status=-1) lets the GDL engine compute normals and edge
neighbors itself; face winding is preserved so consistently wound source
meshes (e.g. after ``recalc_face_normals``) stay outward-oriented.

The geometry is baked (not parametric) — recognisable structures should
prefer the RULED loft path, which produces editable GDL.
"""

from __future__ import annotations

from openbrep.importers.blender_script.loft_gdl import _fmt
from openbrep.importers.blender_script.mesh_capture import CapturedMesh


def generate_mesh_3d(
    mesh: CapturedMesh,
    *,
    scale: float = 1.0,
    source_name: str = "",
    note: str = "",
) -> str:
    """Emit a complete 3d.gdl script as a VERT/EDGE/PGON/BODY body."""
    if not mesh.verts or not mesh.faces:
        raise ValueError("网格为空，无法生成拓扑体")

    lines = [
        f"! Generated by BS2G mesh mode (arbitrary topology): {source_name}",
        f"! Verts: {len(mesh.verts)}, Faces: {len(mesh.faces)}, scale={_fmt(scale)}",
    ]
    if note:
        lines.append(f"! Note: {note}")
    lines.append("")

    for x, y, z in mesh.verts:
        lines.append(f"VERT {_fmt(x * scale)}, {_fmt(y * scale)}, {_fmt(z * scale)}")

    # Unique undirected edges in first-use order; direction = first use.
    edge_index: dict[tuple[int, int], int] = {}
    edge_dir: dict[tuple[int, int], tuple[int, int]] = {}

    def signed_edge(a: int, b: int) -> int:
        key = (a, b) if a < b else (b, a)
        idx = edge_index.get(key)
        if idx is None:
            idx = len(edge_index) + 1  # GDL indices are 1-based
            edge_index[key] = idx
            edge_dir[key] = (a, b)
        return idx if edge_dir[key] == (a, b) else -idx

    face_edges: list[list[int]] = []
    for face in mesh.faces:
        if len(face) < 3:
            continue
        chain = [
            signed_edge(face[i], face[(i + 1) % len(face)])
            for i in range(len(face))
        ]
        face_edges.append(chain)

    for (a, b), idx in sorted(edge_index.items(), key=lambda item: item[1]):
        d0, d1 = edge_dir[(a, b)]
        lines.append(f"EDGE {d0 + 1}, {d1 + 1}, -1, -1, 0")

    for chain in face_edges:
        args = ", ".join(str(e) for e in chain)
        lines.append(f"PGON {len(chain)}, 0, -1, {args}")

    lines.append("BODY -1")
    lines.append("")
    lines.append("END")
    return "\n".join(lines) + "\n"


def mesh_bbox_params(
    mesh: CapturedMesh,
    scale: float = 1.0,
) -> tuple[str, str, str]:
    """Bounding-box dimensions (A, B, ZZYZX) for the paramlist."""
    xs = [p[0] * scale for p in mesh.verts]
    ys = [p[1] * scale for p in mesh.verts]
    zs = [p[2] * scale for p in mesh.verts]
    return (
        _fmt(max(xs) - min(xs)),
        _fmt(max(ys) - min(ys)),
        _fmt(max(zs) - min(zs)),
    )
