import { createStore } from 'zustand/vanilla'
import { createBackendHealth } from './backendHealth'
import {
  addProjectParameter,
  applyParameters,
  askAssistant,
  chooseCompilerFile,
  chooseOutputDirectory,
  chooseProjectDirectory,
  clearAssistantHistory,
  clearProjectMemory,
  closeProject,
  compileProject,
  createProjectFromPrompt,
  deleteMemoryLesson,
  deleteProjectParameter,
  exportHsfProject,
  extractAssistantCodeBlocks,
  fetchConfigRevision,
  fetchKnowledgeStatus,
  fetchMemoryLessons,
  fetchMemoryStatus,
  fetchProjectGitStatus,
  fetchPreview2D,
  fetchPreview,
  fetchRuntimeSettings,
  fetchTapirStatus,
  fetchSnapshot,
  generateWithAssistant,
  generateWithAssistantStream,
  requestModifyPlan,
  confirmModifyPlan,
  confirmSkillProposal,
  getProjectScript,
  initializeProjectGit,
  ignoreMemoryLesson,
  importGdlFile,
  importGsmFile,
  importBlenderScript,
  reloadKnowledge,
  reloadTapirLibraries,
  importAssistantHistory,
  distillAssistantHistory,
  listAssistantHistory,
  listProjectRevisions,
  listProjectScripts,
  listRecentProjects,
  loadProjectPath,
  mockCompile,
  newProject,
  revealArtifact,
  restoreProjectRevision,
  saveProjectRevision,
  saveProject,
  saveProjectScript,
  saveAssistantHistory,
  summarizeProjectMemory,
  syncTapirSelection,
  highlightTapirSelection,
  loadTapirParameters,
  applyTapirParameterEdits,
  updateCompilerSettings,
  updateLlmModel,
  updateLlmApiKey,
  updateSessionLlmModel,
  fetchCodexStatus,
  fetchCodexModels,
  openConfig,
  testLlmConnection,
  updateProjectGitSettings,
  updateMemoryLesson,
  updateProjectParameter,
  validateProjectParameters,
  commitProjectGit,
  workspaceInit,
  workspaceOpen,
  workspaceClose,
  workspaceScan,
  workspaceSearch,
  trashWorkspaceProject,
} from '../api/client'
import { createAssistantActions } from './actions/assistantActions'
import { createCompileActions } from './actions/compileActions'
import { createKnowledgeActions } from './actions/knowledgeActions'
import { createMemoryActions } from './actions/memoryActions'
import { createParameterActions } from './actions/parameterActions'
import { createPreviewActions } from './actions/previewActions'
import { createProjectActions } from './actions/projectActions'
import { createRevisionActions } from './actions/revisionActions'
import { createScriptActions } from './actions/scriptActions'
import { createSettingsActions } from './actions/settingsActions'
import { createTapirActions } from './actions/tapirActions'
import { createWorkspaceActions } from './actions/workspaceActions'
import type { WorkbenchActionContext, WorkbenchApi, WorkbenchSet, WorkbenchState } from './workbenchStoreTypes'
import { defaultLlmSettings } from './workbenchStoreUtils'

export type { WorkbenchApi, WorkbenchState } from './workbenchStoreTypes'

const defaultWorkbenchApi: WorkbenchApi = {
  fetchSnapshot,
  fetchPreview,
  workspaceInit,
  workspaceOpen,
  workspaceClose,
  workspaceScan,
  workspaceSearch,
  trashWorkspaceProject,
  fetchPreview2D,
  loadProjectPath,
  newProject,
  importGdlFile,
  importGsmFile,
  importBlenderScript,
  exportHsfProject,
  saveProject,
  closeProject,
  chooseProjectDirectory,
  chooseCompilerFile,
  chooseOutputDirectory,
  compileProject,
  createProjectFromPrompt,
  listProjectScripts,
  listRecentProjects,
  listProjectRevisions,
  getProjectScript,
  saveProjectScript,
  saveProjectRevision,
  restoreProjectRevision,
  fetchProjectGitStatus,
  initializeProjectGit,
  updateProjectGitSettings,
  commitProjectGit,
  mockCompile,
  revealArtifact,
  updateCompilerSettings,
  fetchRuntimeSettings,
  fetchConfigRevision,
  fetchTapirStatus,
  reloadTapirLibraries,
  syncTapirSelection,
  highlightTapirSelection,
  loadTapirParameters,
  applyTapirParameterEdits,
  openConfig,
  testLlmConnection,
  updateLlmModel,
  updateLlmApiKey,
  updateSessionLlmModel,
  fetchCodexStatus,
  fetchCodexModels,
  askAssistant,
  listAssistantHistory,
  saveAssistantHistory,
  clearAssistantHistory,
  importAssistantHistory,
  distillAssistantHistory,
  extractAssistantCodeBlocks,
  fetchKnowledgeStatus,
  reloadKnowledge,
  fetchMemoryStatus,
  fetchMemoryLessons,
  summarizeProjectMemory,
  deleteMemoryLesson,
  ignoreMemoryLesson,
  updateMemoryLesson,
  clearProjectMemory,
  generateWithAssistant,
  generateWithAssistantStream,
  requestModifyPlan,
  confirmModifyPlan,
  confirmSkillProposal,
  applyParameters,
  addProjectParameter,
  updateProjectParameter,
  deleteProjectParameter,
  validateProjectParameters,
}

export function createWorkbenchStore(api: WorkbenchApi = defaultWorkbenchApi) {
  return createStore<WorkbenchState>((set, get) => {
    const context: WorkbenchActionContext = {
      api,
      get,
      set: set as WorkbenchSet,
    }
    // 后端健康看门狗：失败分型 + 3s 恢复轮询 + 成功自动清横幅
    createBackendHealth({ get, set: set as WorkbenchSet }).install()
    return {
      ...initialWorkbenchState(),
      ...createProjectActions(context),
      ...createSettingsActions(context),
      ...createTapirActions(context),
      ...createWorkspaceActions(context),
      ...createParameterActions(context),
      ...createPreviewActions(context),
      ...createCompileActions(context),
      ...createKnowledgeActions(context),
      ...createMemoryActions(context),
      ...createScriptActions(context),
      ...createRevisionActions(context),
      ...createAssistantActions(context),
      clearLastError() {
        set({ lastError: null })
      },
    }
  })
}

export const workbenchStore = createWorkbenchStore()

function initialWorkbenchState() {
  return {
    sessionId: null,
    projectEpoch: 0,
    project: null,
    parameters: [],
    parameterIssues: [],
    draftParameters: {},
    preview: null,
    preview2d: null,
    previewQuality: 'fast' as const,
    previewGhost: null,
    previewGhostLabel: null,
    warnings: [],
    loading: false,
    applying: false,
    compiling: false,
    lastError: null,
    backendError: null,
    backendNotice: null,
    compileLog: [],
    compilerSettings: { mode: 'mock' as const, converter_path: '', output_dir: '' },
    llmSettings: defaultLlmSettings(),
    codexCatalog: { connected: false, models: [], loaded: false },
    configRevision: null,
    chatAbortController: null,
    interruptedContext: null,
    activeRailPanel: '3d' as const,
    assistantBusy: false,
    assistantMessages: [],
    assistantDraftSeed: null,
    pendingPlan: null,
    pendingExtraction: null,
    pendingSkillProposal: null,
    scripts: [],
    recentProjects: [],
    revisions: [],
    gitStatus: null,
    gitBusy: false,
    knowledgeStatus: null,
    knowledgeBusy: false,
    memoryStatus: null,
    memoryLessons: [],
    memorySkillPreview: '',
    memoryBusy: false,
    tapirStatus: null,
    tapirBusy: false,
    latestRevisionId: null,
    revisionLoading: false,
    activeScriptName: null,
    scriptContents: {},
    dirtyScripts: {},
    lastSavedAt: null,
    needsSaveAs: false,
    scriptLoading: false,
    scriptSaving: false,
    mockCompileResult: null,
    workspace: null,
    workspaceBusy: false,
    workspaceInitHint: null,
    workspaceSearching: false,
    workspaceSearchQuery: null,
    workspaceSearchHits: [],
    workspaceSearchResult: null,
  }
}
