import { createStore } from 'zustand/vanilla'
import {
  addProjectParameter,
  applyParameters,
  askAssistant,
  chooseCompilerFile,
  chooseOutputDirectory,
  chooseProjectDirectory,
  clearAssistantHistory,
  clearProjectMemory,
  closeProject,
  compileProject,
  createProjectFromPrompt,
  deleteMemoryLesson,
  deleteProjectParameter,
  exportHsfProject,
  extractAssistantCodeBlocks,
  fetchMemoryLessons,
  fetchMemoryStatus,
  fetchProjectGitStatus,
  fetchPreview2D,
  fetchPreview,
  fetchRuntimeSettings,
  fetchTapirStatus,
  fetchSnapshot,
  generateWithAssistant,
  getProjectScript,
  initializeProjectGit,
  ignoreMemoryLesson,
  importGdlFile,
  importGsmFile,
  reloadTapirLibraries,
  listAssistantHistory,
  listProjectRevisions,
  listProjectScripts,
  listRecentProjects,
  loadProjectPath,
  mockCompile,
  newProject,
  revealArtifact,
  restoreProjectRevision,
  saveProjectRevision,
  saveProject,
  saveProjectScript,
  saveAssistantHistory,
  summarizeProjectMemory,
  syncTapirSelection,
  highlightTapirSelection,
  loadTapirParameters,
  applyTapirParameterEdits,
  updateCompilerSettings,
  openConfig,
  testLlmConnection,
  updateProjectGitSettings,
  updateMemoryLesson,
  updateProjectParameter,
  validateProjectParameters,
  commitProjectGit,
} from '../api/client'
import { createAssistantActions } from './actions/assistantActions'
import { createCompileActions } from './actions/compileActions'
import { createMemoryActions } from './actions/memoryActions'
import { createParameterActions } from './actions/parameterActions'
import { createPreviewActions } from './actions/previewActions'
import { createProjectActions } from './actions/projectActions'
import { createRevisionActions } from './actions/revisionActions'
import { createScriptActions } from './actions/scriptActions'
import { createSettingsActions } from './actions/settingsActions'
import { createTapirActions } from './actions/tapirActions'
import type { WorkbenchActionContext, WorkbenchApi, WorkbenchSet, WorkbenchState } from './workbenchStoreTypes'
import { defaultLlmSettings } from './workbenchStoreUtils'

export type { WorkbenchApi, WorkbenchState } from './workbenchStoreTypes'

const defaultWorkbenchApi: WorkbenchApi = {
  fetchSnapshot,
  fetchPreview,
  fetchPreview2D,
  loadProjectPath,
  newProject,
  importGdlFile,
  importGsmFile,
  exportHsfProject,
  saveProject,
  closeProject,
  chooseProjectDirectory,
  chooseCompilerFile,
  chooseOutputDirectory,
  compileProject,
  createProjectFromPrompt,
  listProjectScripts,
  listRecentProjects,
  listProjectRevisions,
  getProjectScript,
  saveProjectScript,
  saveProjectRevision,
  restoreProjectRevision,
  fetchProjectGitStatus,
  initializeProjectGit,
  updateProjectGitSettings,
  commitProjectGit,
  mockCompile,
  revealArtifact,
  updateCompilerSettings,
  fetchRuntimeSettings,
  fetchTapirStatus,
  reloadTapirLibraries,
  syncTapirSelection,
  highlightTapirSelection,
  loadTapirParameters,
  applyTapirParameterEdits,
  openConfig,
  testLlmConnection,
  askAssistant,
  listAssistantHistory,
  saveAssistantHistory,
  clearAssistantHistory,
  extractAssistantCodeBlocks,
  fetchMemoryStatus,
  fetchMemoryLessons,
  summarizeProjectMemory,
  deleteMemoryLesson,
  ignoreMemoryLesson,
  updateMemoryLesson,
  clearProjectMemory,
  generateWithAssistant,
  applyParameters,
  addProjectParameter,
  updateProjectParameter,
  deleteProjectParameter,
  validateProjectParameters,
}

export function createWorkbenchStore(api: WorkbenchApi = defaultWorkbenchApi) {
  return createStore<WorkbenchState>((set, get) => {
    const context: WorkbenchActionContext = {
      api,
      get,
      set: set as WorkbenchSet,
    }
    return {
      ...initialWorkbenchState(),
      ...createProjectActions(context),
      ...createSettingsActions(context),
      ...createTapirActions(context),
      ...createParameterActions(context),
      ...createPreviewActions(context),
      ...createCompileActions(context),
      ...createMemoryActions(context),
      ...createScriptActions(context),
      ...createRevisionActions(context),
      ...createAssistantActions(context),
      clearLastError() {
        set({ lastError: null })
      },
    }
  })
}

export const workbenchStore = createWorkbenchStore()

function initialWorkbenchState() {
  return {
    sessionId: null,
    projectEpoch: 0,
    project: null,
    parameters: [],
    parameterIssues: [],
    draftParameters: {},
    preview: null,
    preview2d: null,
    warnings: [],
    loading: false,
    applying: false,
    compiling: false,
    lastError: null,
    compileLog: [],
    compilerSettings: { mode: 'mock' as const, converter_path: '', output_dir: '' },
    llmSettings: defaultLlmSettings(),
    activeRailPanel: '3d' as const,
    assistantBusy: false,
    assistantMessages: [],
    scripts: [],
    recentProjects: [],
    revisions: [],
    gitStatus: null,
    gitBusy: false,
    memoryStatus: null,
    memoryLessons: [],
    memorySkillPreview: '',
    memoryBusy: false,
    tapirStatus: null,
    tapirBusy: false,
    latestRevisionId: null,
    revisionLoading: false,
    activeScriptName: null,
    scriptContents: {},
    dirtyScripts: {},
    lastSavedAt: null,
    scriptLoading: false,
    scriptSaving: false,
    mockCompileResult: null,
  }
}
